In [ ]:
# 

In [155]:
import os ##işletim sistemi ile ilgili görevleri yapıyor

In [156]:
os.listdir() ##içeriği listeliyor  

['.ipynb_checkpoints',
 '4.3_notebook_quizz_pandas.ipynb',
 'Automobile_data.csv',
 'data üzerinde pandas ve regresyon çalışmaları.ipynb',
 'Decisin Tree Regression.ipynb',
 'Decision Tree',
 'Decision Tree Classificaiton.ipynb',
 'Decision Tree Classificationn_murat.ipynb',
 'Decision_Tree_Reg.xlsx',
 'KNN Regression.ipynb',
 'Krill KNeighbors.ipynb',
 'Krill LogReg.ipynb',
 'Krill Naive Bayes Classification.ipynb',
 'Krill SVM.ipynb',
 'Linear Regression.ipynb',
 'Logistic_regression.ipynb',
 'meyve_agırlıkları_arastırması.csv',
 'multiple linear regression.ipynb',
 'Naive Bayes.ipynb',
 'nearest neigbour.ipynb',
 'Numpy Temel Konular (1).ipynb',
 'Numpy Temel Konular (2).ipynb',
 'Numpy Temel Konular.ipynb',
 'optimizer_data.csv',
 'pandas_calışma.ipynb',
 'Polinomial2-Copy1.ipynb',
 'Polinomial2.ipynb',
 'PreprocessingAndDecisionTree.pk',
 'PY0101EN-4-3-LoadData.ipynb',
 'Random Forest Classification.ipynb',
 'Random Forest Regression.rar',
 'RandomForest.ipynb',
 'S2upport Vector 

In [157]:
ham_dir="..\..\Downloads\enron\enron{}\ham".format(1) # mutlak yol olarak de verebiliriz.
ham_dir

'..\\..\\Downloads\\enron\\enron1\\ham'

In [158]:
os.getcwd() ##current working directory

'C:\\Users\\gold\\Downloads\\python çalışmalar'

In [159]:
ham_list=[]
for mail in os.listdir(ham_dir):
    with open("{}\{}".format(ham_dir,mail),"r", encoding='ansi') as file:
        scan_mail=file.read()
        ham_list.append(scan_mail)
#print(scan_mail)
#print(scanned_list[5])

In [160]:
len(ham_list)

3672

In [161]:
sample_mail=ham_list[9]
print(sample_mail)

Subject: re : entex transistion
thanks so much for the memo . i would like to reiterate my support on two key
issues :
1 ) . thu - best of luck on this new assignment . howard has worked hard and
done a great job ! please don ' t be shy on asking questions . entex is
critical to the texas business , and it is critical to our team that we are
timely and accurate .
2 ) . rita : thanks for setting up the account team . communication is
critical to our success , and i encourage you all to keep each other informed
at all times . the p & l impact to our business can be significant .
additionally , this is high profile , so we want to assure top quality .
thanks to all of you for all of your efforts . let me know if there is
anything i can do to help provide any additional support .
rita wynne
12 / 14 / 99 02 : 38 : 45 pm
to : janet h wallis / hou / ect @ ect , ami chokshi / corp / enron @ enron , howard b
camp / hou / ect @ ect , thu nguyen / hou / ect @ ect , kyle r lilly / hou / ect @ ect 

In [162]:
import re #regular expressions

In [163]:
def delete(s):
    pattern="[^A-Za-z]"
    return re.sub(pattern, " ", s)

In [164]:
delete(sample_mail)

'Subject  re   entex transistion thanks so much for the memo   i would like to reiterate my support on two key issues         thu   best of luck on this new assignment   howard has worked hard and done a great job   please don   t be shy on asking questions   entex is critical to the texas business   and it is critical to our team that we are timely and accurate         rita   thanks for setting up the account team   communication is critical to our success   and i encourage you all to keep each other informed at all times   the p   l impact to our business can be significant   additionally   this is high profile   so we want to assure top quality   thanks to all of you for all of your efforts   let me know if there is anything i can do to help provide any additional support   rita wynne                           pm to   janet h wallis   hou   ect   ect   ami chokshi   corp   enron   enron   howard b camp   hou   ect   ect   thu nguyen   hou   ect   ect   kyle r lilly   hou   ect   ect

In [165]:
spam_dir="..\..\Downloads\enron\enron{}\spam".format(1) # mutlak yol olarak de verebiliriz.
spam_dir

'..\\..\\Downloads\\enron\\enron1\\spam'

In [166]:
spam_list=[]
for mail in os.listdir(spam_dir):
    with open("{}\{}".format(spam_dir,mail),"r", encoding='ansi') as file:
        scan_mail=file.read()
        spam_list.append(scan_mail)
#print(scan_mail)
print(spam_list[9])

Subject: ^ . pe , nis s ^ ize mat ; ters ! yhvqbvdboevkcd
briababhdpr frdjvdbesk cdpizacqjkufx hfkosxcymgftzd wdyiwpbqipv xxieqncfpa
the only solution to penis enlargement
fxbekdcaolk gsiaagcrhyp
limited offer : add at least 3 inches or get your money back !
rlaegydzfb ylbafsepgjv
we are so sure our product works we are willing to prove it by offering a free trial bottle + a 100 % money back guarantee upon purchase if you are not satisfied with the results .
- - - > click here to learn more - - -
also check out our * brand new * product : penis enlargement patches
comes with the 100 % money back warranty as well !
eqiupgbbaxz gogqkkdpbdo
igjohodzauuuu yreliodctrin
cbywdvdthl nogsvvbnwug
no more offers



In [167]:
sample_spam_mail=spam_list[9]
print(sample_spam_mail)

Subject: ^ . pe , nis s ^ ize mat ; ters ! yhvqbvdboevkcd
briababhdpr frdjvdbesk cdpizacqjkufx hfkosxcymgftzd wdyiwpbqipv xxieqncfpa
the only solution to penis enlargement
fxbekdcaolk gsiaagcrhyp
limited offer : add at least 3 inches or get your money back !
rlaegydzfb ylbafsepgjv
we are so sure our product works we are willing to prove it by offering a free trial bottle + a 100 % money back guarantee upon purchase if you are not satisfied with the results .
- - - > click here to learn more - - -
also check out our * brand new * product : penis enlargement patches
comes with the 100 % money back warranty as well !
eqiupgbbaxz gogqkkdpbdo
igjohodzauuuu yreliodctrin
cbywdvdthl nogsvvbnwug
no more offers



In [168]:
delete(spam_list[9])

'Subject      pe   nis s   ize mat   ters   yhvqbvdboevkcd briababhdpr frdjvdbesk cdpizacqjkufx hfkosxcymgftzd wdyiwpbqipv xxieqncfpa the only solution to penis enlargement fxbekdcaolk gsiaagcrhyp limited offer   add at least   inches or get your money back   rlaegydzfb ylbafsepgjv we are so sure our product works we are willing to prove it by offering a free trial bottle   a       money back guarantee upon purchase if you are not satisfied with the results           click here to learn more       also check out our   brand new   product   penis enlargement patches comes with the       money back warranty as well   eqiupgbbaxz gogqkkdpbdo igjohodzauuuu yreliodctrin cbywdvdthl nogsvvbnwug no more offers '

In [169]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
import numpy as np

In [170]:
nltk.download('stopwords') # Download stopwords so irrelevant words won't affect our algorithm

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gold\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [171]:
from nltk.corpus import stopwords

In [172]:
stop=set(stopwords.words("english"))
stop

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [173]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [174]:
def remove_stopwords(s):
    word_list=s.split()
    clean_word_list=[ps.stem(word).lower() for word in word_list if word not in stop]
    return " ".join(clean_word_list)

In [175]:
liste=ham_list+spam_list

In [176]:
processed_list=[remove_stopwords(delete(mail)) for mail in liste]
processed_list[0]

'subject christma tree farm pictur'

In [177]:
labels=len(ham_list)*[0]+len(spam_list)*[1]
len(labels)

5172

In [178]:
remove_stopwords(delete(sample_mail))

'subject entex transist thank much memo would like reiter support two key issu thu best luck new assign howard work hard done great job pleas shi ask question entex critic texa busi critic team time accur rita thank set account team commun critic success encourag keep inform time p l impact busi signific addit high profil want assur top qualiti thank effort let know anyth help provid addit support rita wynn pm janet h walli hou ect ect ami chokshi corp enron enron howard b camp hou ect ect thu nguyen hou ect ect kyle r lilli hou ect ect stacey neuweil hou ect ect georg grant hou ect ect juli meyer hou ect ect cc daren j farmer hou ect ect kathryn cord hou ect ect rita wynn hou ect lisa csiko hou ect ect brenda f herod hou ect ect pamela chamber corp enron enron subject entex transist purpos email recap kickoff meet held yesterday member commerci volum manag concernig entex account effect januari thu nguyen x volum manag group take respons alloc entex contract howard thu began train mon

In [179]:
vectorizer=CountVectorizer(max_features=1500)

In [180]:
x = vectorizer.fit_transform(processed_list).toarray()
x.shape # herbir satır mail, herbir kolonda da kelimeler var o mailde kaç defa geçtiğini gösteriyor

(5172, 1500)

In [181]:
vectorizer.get_feature_names()

['abil',
 'abl',
 'accept',
 'access',
 'accord',
 'account',
 'acquir',
 'acquisit',
 'across',
 'act',
 'action',
 'activ',
 'acton',
 'actual',
 'ad',
 'add',
 'addit',
 'address',
 'adjust',
 'administr',
 'adob',
 'advanc',
 'advantag',
 'advertis',
 'advic',
 'advis',
 'advisor',
 'aep',
 'aepin',
 'affect',
 'affili',
 'afford',
 'afternoon',
 'age',
 'agenc',
 'agent',
 'ago',
 'agre',
 'agreement',
 'aime',
 'air',
 'al',
 'albrecht',
 'alert',
 'ali',
 'align',
 'allen',
 'alloc',
 'allow',
 'along',
 'alreadi',
 'also',
 'altern',
 'alway',
 'america',
 'american',
 'ami',
 'amount',
 'analysi',
 'analyst',
 'anita',
 'announc',
 'annual',
 'anoth',
 'answer',
 'anticip',
 'anyon',
 'anyth',
 'aol',
 'apach',
 'appear',
 'appli',
 'applic',
 'appreci',
 'appropri',
 'approv',
 'approxim',
 'apr',
 'april',
 'archer',
 'area',
 'around',
 'arrang',
 'asap',
 'ask',
 'asset',
 'assign',
 'assist',
 'associ',
 'assum',
 'assumpt',
 'assur',
 'attach',
 'attend',
 'attent',
 'au

In [182]:
np.unique(x) #kelimelerin ne kadar geçtiğini gösteriyor

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  77,  78,  82,
        83,  84,  85,  86,  87,  89,  90,  91,  93,  94,  95,  97, 102,
       105, 106, 109, 121, 128, 130, 133, 134, 135, 138, 146, 154, 156,
       165, 167, 169, 177, 180, 233, 273, 313, 340, 342, 701], dtype=int64)

In [183]:
import pandas as pd

In [184]:
X = pd.DataFrame(data=x,columns=vectorizer.get_feature_names())
X["label"]=labels

In [185]:
X_group=X.groupby(by="label").mean()
X_group

abil       abl    accept    access    accord   account    acquir  \
label                                                                         
0      0.014161  0.052832  0.013617  0.053377  0.019063  0.093410  0.002451   
1      0.028000  0.035333  0.056000  0.052000  0.020667  0.167333  0.036000   

       acquisit    across       act  ...     xp     yahoo        ye      year  \
label                                ...                                        
0      0.004085  0.013617  0.008442  ...  0.000  0.028322  0.014978  0.082789   
1      0.043333  0.007333  0.137333  ...  0.112  0.032667  0.016667  0.139333   

       yesterday       yet     young     yvett      zero      zone  
label                                                               
0       0.018519  0.031590  0.058279  0.015251  0.055011  0.025599  
1       0.005333  0.018667  0.030000  0.001333  0.013333  0.041333  

[2 rows x 1500 columns]

In [186]:
X["label"].value_counts()

0    3672
1    1500
Name: label, dtype: int64

In [187]:
X["label"].value_counts()/X.shape[0]

0    0.709977
1    0.290023
Name: label, dtype: float64

In [188]:
((X_group.loc[0])/(X_group.loc[1])).sort_values(ascending=False).head()

goliad     inf
dth        inf
daren      inf
neon       inf
neuweil    inf
dtype: float64

In [189]:
((X_group.loc[0])/(X_group.loc[1])).sort_values(ascending=False).tail()

specul      0.0
oo          0.0
ook         0.0
paliourg    0.0
knle        0.0
dtype: float64

In [190]:
birler=np.ones((2,1500))

In [191]:
x_smooth=np.concatenate((x, birler),axis=0)
x_smooth

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [192]:
y_smooth=labels+[0,1]

In [193]:
X_group=pd.DataFrame(data=x_smooth,columns=vectorizer.get_feature_names())
X_group["labels"]=y_smooth

In [194]:
X_group=X_group.groupby("labels").mean()

In [195]:
((X_group.loc[0])/(X_group.loc[1])).sort_values(ascending=False)

enron           2679.160359
hpl              947.677375
daren            777.267084
mmbtu            575.798802
ect              473.293811
sitara           352.263000
hou              330.649545
pec              307.719303
ena              299.546148
meter            277.785121
nom              242.334059
melissa          189.208549
teco             181.852709
tenaska          176.540158
pat              163.054451
aime             146.299483
hsc              135.265723
cotten           131.587803
counterparti     128.318541
chokshi          126.275252
fyi              122.188674
hplc             119.736727
wellhead         117.693439
clyne            113.198203
eastran          111.972230
txu               96.443234
hplno             91.947999
rita              91.130683
lannou            90.722026
buyback           81.731555
                   ...     
hotlist            0.005522
moopid             0.005522
div                0.005449
valign             0.005108
img                0

In [196]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB

In [197]:
modelM=MultinomialNB()
modelG=GaussianNB()
modelM.fit(x_smooth,y_smooth)
modelG.fit(x_smooth,y_smooth)

GaussianNB(priors=None, var_smoothing=1e-09)

In [198]:
print(modelM.score(x,labels))
print(modelG.score(x,labels))

0.9371616395978345
0.9609435421500386


In [199]:
from sklearn.metrics import confusion_matrix

In [200]:
cmM=confusion_matrix(labels,modelM.predict(x))
cmM

array([[3447,  225],
       [ 100, 1400]], dtype=int64)

In [201]:
cmG=confusion_matrix(labels,modelG.predict(x))
cmG

array([[3480,  192],
       [  10, 1490]], dtype=int64)

In [202]:
#  3452,  220 gerçek  ham mailler
#  107, 1393  gerçek spam mailler
#  

In [1]:
3480 / (3480 + 10) # recall

0.997134670487106

In [2]:
3480 / (3480 + 192) # precision

0.9477124183006536

In [203]:
# enron6 için aynı işlemleri uygula ve predict score ve confusion_maxtirx değerlendir

In [204]:
import sys

In [205]:
sys.path.append("C:\\Users\\gold\\Desktop\\python programcıklar")

In [217]:
del sys.modules["spam_utils"]

In [218]:
from spam_utils import *

In [206]:
ham_dir6="..\..\Downloads\enron\enron{}\ham".format(6) # mutlak yol olarak de verebiliriz.
ham_dir6

'..\\..\\Downloads\\enron\\enron6\\ham'

In [208]:
ham_list6=read_ham(ham_dir6)
ham_list6[0]

"Subject: key dates and impact of upcoming sap implementation\nover the next few weeks , project apollo and beyond will conduct its final sap\nimplementation \x01 ) this implementation will impact approximately 12 , 000 new\nusers plus all existing system users . sap brings a new dynamic to enron ,\nenhancing the timely flow and sharing of specific project , human resources ,\nprocurement , and financial information across business units and across\ncontinents .\nthis final implementation will retire multiple , disparate systems and replace\nthem with a common , integrated system encompassing many processes including\npayroll , timekeeping , benefits , project management , and numerous financial\nprocesses .\nemployees will be empowered to update and / or view their personal information\nvia the intranet - based ehronline - - a single front - end to sap ' s self service\nfunctionality and enron ' s global information system ( gis ) . among other\nthings , individuals will be able to up

In [209]:
spam_dir6="..\..\Downloads\enron\enron{}\spam".format(6) # mutlak yol olarak de verebiliriz.
spam_dir6

'..\\..\\Downloads\\enron\\enron6\\spam'

In [210]:
spam_list6=read_spam(spam_dir6)
spam_list6[0]

'Subject: advs\ngreetings ,\ni am benedicta lindiwe hendricks ( mrs ) of rsa . i am writing\nthis letter to you with the hope that you will be kind enough\nto assist my family .\nif this means of communication is not acceptable to you please\naccept my apologies as it is the only available and resourceful\nmeans for me right now .\nmy children and i are in need of your assistance and we sincerely\npray and hope that you will be able to attend to our request .\nif there is the possibility that you will be able to help us do\nkindly let me know by return mail so that i can tell you about\nour humble request .\nthank for your understanding .\nbenedicta lindiwe hendricks ( mrs ) .\nplease reply to this email address ; heno 0 @ katamail . com'

In [212]:
liste6=ham_list6+spam_list6

In [220]:
processed_list6=[remove_StopWords(mail) for mail in liste6]
processed_list6[0]

'subject key date impact upcom sap implement next week project apollo beyond conduct final sap implement implement impact approxim new user plu exist system user sap bring new dynam enron enhanc time flow share specif project human resourc procur financi inform across busi unit across contin final implement retir multipl dispar system replac common integr system encompass mani process includ payrol timekeep benefit project manag numer financi process employe empow updat view person inform via intranet base ehronlin singl front end sap self servic function enron global inform system gi among thing individu abl updat person inform includ w address person bank inform manag individu time use new time entri tool view benefit elect view person payrol inform line enron employe paid corpor payrol houston exclud azurix employe financi commun enron energi servic enron invest partner enron north america enron renew energi corpor ga pipelin group global financ global enron network global product p

In [221]:
y_test=create_labels(ham_list6,spam_list6)
y_test

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [222]:
# test set üzerinde inceleme yparken sadece transform yapıyoruz

In [223]:
x_test=vectorizer.transform(processed_list6).toarray()
x_test

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [224]:
print(modelM.score(x_test,y_test))
print(modelG.score(x_test,y_test))

0.9158333333333334
0.9341666666666667


In [226]:
cmG=confusion_matrix(y_test,modelG.predict(x_test))
cmG

array([[1208,  292],
       [ 103, 4397]], dtype=int64)

In [227]:
# How do you account for different prior probabilities for spam and ham
# 

In [228]:
modelM=MultinomialNB()
modelG=GaussianNB(priors=(0.5,0.5))
modelM.fit(x_smooth,y_smooth)
modelG.fit(x_smooth,y_smooth)

GaussianNB(priors=(0.5, 0.5), var_smoothing=1e-09)

In [229]:
print(modelM.score(x_test,y_test))
print(modelG.score(x_test,y_test)) # laplace smoothing scoreları

0.9158333333333334
0.934


In [230]:
cmG=confusion_matrix(y_test,modelG.predict(x_test))
cmG

array([[1207,  293],
       [ 103, 4397]], dtype=int64)

In [231]:
modelM=MultinomialNB()
modelG=GaussianNB()
modelM.fit(x,labels)
modelG.fit(x,labels)

GaussianNB(priors=None, var_smoothing=1e-09)

In [232]:
print(modelM.score(x,labels))
print(modelG.score(x,labels))

0.9392884764114462
0.9537896365042536


In [233]:
print(modelM.score(x_test,y_test))
print(modelG.score(x_test,y_test)) # without laplace smoothing

0.918
0.925


In [234]:
# What are the most discriminative words based on the learned probabilities?

In [235]:
((X_group.loc[0])/(X_group.loc[1])).sort_values(ascending=False)

enron           2679.160359
hpl              947.677375
daren            777.267084
mmbtu            575.798802
ect              473.293811
sitara           352.263000
hou              330.649545
pec              307.719303
ena              299.546148
meter            277.785121
nom              242.334059
melissa          189.208549
teco             181.852709
tenaska          176.540158
pat              163.054451
aime             146.299483
hsc              135.265723
cotten           131.587803
counterparti     128.318541
chokshi          126.275252
fyi              122.188674
hplc             119.736727
wellhead         117.693439
clyne            113.198203
eastran          111.972230
txu               96.443234
hplno             91.947999
rita              91.130683
lannou            90.722026
buyback           81.731555
                   ...     
hotlist            0.005522
moopid             0.005522
div                0.005449
valign             0.005108
img                0

In [236]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [237]:
p=precision_score(y_test,modelG.predict(x_test)) # spam dediklerimizn gerçekte ne kadarı spam
p

0.9297538200339559

In [238]:
r=recall_score(y_test,modelG.predict(x_test)) # bütün spamlein ne kadarını doğru tahmin ettik
r

0.9735555555555555

In [239]:
f1_score(y_test,modelG.predict(x_test))

0.9511506730351715

In [241]:
sample_mail

'Subject: re : entex transistion\nthanks so much for the memo . i would like to reiterate my support on two key\nissues :\n1 ) . thu - best of luck on this new assignment . howard has worked hard and\ndone a great job ! please don \' t be shy on asking questions . entex is\ncritical to the texas business , and it is critical to our team that we are\ntimely and accurate .\n2 ) . rita : thanks for setting up the account team . communication is\ncritical to our success , and i encourage you all to keep each other informed\nat all times . the p & l impact to our business can be significant .\nadditionally , this is high profile , so we want to assure top quality .\nthanks to all of you for all of your efforts . let me know if there is\nanything i can do to help provide any additional support .\nrita wynne\n12 / 14 / 99 02 : 38 : 45 pm\nto : janet h wallis / hou / ect @ ect , ami chokshi / corp / enron @ enron , howard b\ncamp / hou / ect @ ect , thu nguyen / hou / ect @ ect , kyle r lilly 

In [256]:
def production(mail):
    mail=remove_StopWords(mail)
    mail_vectorized=vectorizer.transform([mail]).toarray()
    pred_dict={0:"ham",1:"spam"}
    return pred_dict[modelG.predict(mail_vectorized)[0]]

In [280]:
production("hi i am yusuf. 3, 6, ?, !, vi, ect, drugs's, enron, ")

'spam'

In [281]:
production(ham_list6[163])

'spam'

In [282]:
import pickle

In [283]:
pickle.dump(modelG,open("spam_classifier.pickle","wb"))

In [284]:
pickle.dump(vectorizer,open("spam_classifier_vectorizer.pickle","wb"))